# Generated by Django 4.2 on 2024-09-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamixin',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Введите время создания', verbose_name='Время'),
        ),
    ]
