# Generated by Django 4.2 on 2024-09-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_network', '0002_alter_datamixin_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamixin',
            name='dept',
            field=models.PositiveIntegerField(default=0, help_text='Введите задолженность перед поставщиком', verbose_name='Задолженность'),
        ),
    ]
