# Generated by Django 4.2 on 2024-09-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_network', '0003_alter_datamixin_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamixin',
            name='dept',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Введите задолженность перед поставщиком', max_digits=8, verbose_name='Задолженность'),
        ),
    ]
